# Generated by Django 4.2.5 on 2023-11-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('zw', models.CharField(max_length=10)),
                ('pinyin', models.CharField(max_length=10)),
            ],
        ),
    ]
