version: '3'
services:

  web:
      build: .
      depends_on:
        - postgres
      container_name: zhongwen
      volumes:
      - .:/zhongwen
      - static:/zhongwen/staticfiles
      - media:/zhongwen/media
      expose:
        - 8000
      command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 zhongwen.wsgi -b 0.0.0.0:8000"

  postgres:
      build: ./postgres
      restart: unless-stopped
      expose:
        - "5432"
      environment:   # will be used by the init script
        LC_ALL: C.UTF-8
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_PASSWORD: POSTGRES_PASSWORD
        POSTGRES_DB: POSTGRES_DB
      volumes:
        - pgdata:/var/lib/postgresql/data/  

  nginx:
      restart: always
      build: ./nginx/
      volumes: 
        - ./nginx/:/etc/nginx/conf.d
        - ./logs/:/zhongwen/logs
        - static:/zhongwen/static_cdn
        - media:/zhongwen/media_cdn
      ports: 
        - "1221:80"
      links:
        - web 

volumes:
  pgdata:
  media:
  static: