version: "3"
services:
  zhongwen:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./zhongwen:/zhongwen
    command: python manage.py runserver --insecure 0.0.0.0:8000
    env_file:
      - .env
volumes:
  pgdata: