version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"  # Expose the PostgreSQL port if needed
    volumes:
      - pgdata:/var/lib/postgresql/data
  zhongwen:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./zhongwen:/zhongwen
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env
volumes:
  pgdata: