# Generated by Django 4.2.5 on 2023-11-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=20)),
                ('es', models.CharField(max_length=20)),
                ('zw', models.CharField(max_length=20)),
                ('pinyin', models.CharField(max_length=20)),
                ('pronun', models.CharField(max_length=100)),
            ],
        ),
    ]
