# Generated by Django 4.2.5 on 2023-11-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pronun',
        ),
    ]
